"""API route declarations.

Grouped endpoints:
    Auth: register/, login/
    Feed: news_feed/
    Posts: posts/ (create), posts/<id>/ (update/delete), posts/<id>/share/
    Comments: posts/<id>/comments/ (create), posts/<id>/comments/list/ (list), comments/<id>/ (update/delete)
    Shares: posts/<id>/shares/ (list), shares/<id>/ (update/delete)
    Search: search/
    User stats: my_stats/
    Uploads: upload_image/
"""

from django.urls import path
from . import views

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    # Current user (lightweight profile for frontend gating)
    path('users/me', views.current_user, name='current_user'),
    # Public user profile (read-only)
    path('users/<int:user_id>', views.get_user_public, name='get_user_public'),
    # Current user profile update (bio, avatar)
    path('users/me/update', views.update_current_user, name='update_current_user'),
    # User relations & posts
    path('users/<int:user_id>/follow', views.follow_user, name='follow_user'),
    path('users/<int:user_id>/unfollow', views.unfollow_user, name='unfollow_user'),
    path('users/<int:user_id>/posts', views.list_user_posts, name='list_user_posts'),
    path('users/<int:user_id>/activity', views.list_user_activity, name='list_user_activity'),
    path('users/<int:user_id>/organizations', views.list_user_organizations, name='list_user_organizations'),
    path('users/upgrade/fire-service', views.upgrade_fire_service, name='upgrade_fire_service'),
    path('news_feed/', views.news_feed, name='news_feed'),
    path('posts/', views.create_post, name='create_post'),
    path('posts/<int:post_id>/', views.post_item, name='post_item'),
    path('posts/<int:post_id>/share/', views.share_post, name='share_post'),
    path('posts/<int:post_id>/comments/', views.create_comment, name='create_comment'),
    path('posts/<int:post_id>/comments/list/', views.list_comments, name='list_comments'),
    path('posts/<int:post_id>/shares/', views.list_shares, name='list_shares'),
    path('shares/<int:share_id>/', views.share_item, name='share_item'),
    path('comments/<int:comment_id>/', views.comment_item, name='comment_item'),
    path('search/', views.search, name='search'),
    path('my_stats/', views.my_stats, name='my_stats'),
    path('upload_image/', views.upload_image, name='upload_image'),
    # AI assistant (stateless chat)
    path('ai/chat', views.ai_chat, name='ai_chat'),
    path('ai/models', views.ai_models, name='ai_models'),
    path('ai/pull', views.ai_pull_model, name='ai_pull_model'),
    path('ai/health', views.ai_health, name='ai_health'),
    # Admin approval routes removed (org accounts auto-active now)
    path('hospitals/<int:hospital_id>/doctors/add', views.add_doctor_to_hospital, name='add_doctor_to_hospital'),
    path('hospitals/<int:hospital_id>/doctors/remove', views.remove_doctor_from_hospital, name='remove_doctor_from_hospital'),
    path('doctors/profile/set', views.set_doctor_profile, name='set_doctor_profile'),
    path('hospitals/<int:hospital_id>/doctors', views.list_hospital_doctors, name='list_hospital_doctors'),
    path('hospitals/<int:hospital_id>/schedule/add', views.add_doctor_schedule, name='add_doctor_schedule'),
    path('hospitals/<int:hospital_id>/schedule/<int:schedule_id>/update', views.update_doctor_schedule, name='update_doctor_schedule'),
    path('hospitals/<int:hospital_id>/schedule/<int:schedule_id>/delete', views.delete_doctor_schedule, name='delete_doctor_schedule'),
    path('hospitals/<int:hospital_id>/services/add', views.add_hospital_service, name='add_hospital_service'),
    path('hospitals/<int:hospital_id>/services/list', views.list_hospital_services, name='list_hospital_services'),
    path('hospitals/<int:hospital_id>/services/<int:service_id>/update', views.update_hospital_service, name='update_hospital_service'),
    path('hospitals/<int:hospital_id>/services/<int:service_id>/delete', views.delete_hospital_service, name='delete_hospital_service'),
    path('services/book', views.book_service, name='book_service'),
    path('services/mine', views.list_my_service_bookings, name='list_my_service_bookings'),
    path('services/hospital/bookings', views.list_hospital_service_bookings, name='list_hospital_service_bookings'),
    path('services/bookings/<int:booking_id>/confirm', views.confirm_service_booking, name='confirm_service_booking'),
    path('services/bookings/<int:booking_id>/decline', views.decline_service_booking, name='decline_service_booking'),
    path('services/bookings/<int:booking_id>/cancel/request', views.request_cancel_service_booking, name='request_cancel_service_booking'),
    path('services/bookings/<int:booking_id>/cancel/approve', views.approve_cancel_service_booking, name='approve_cancel_service_booking'),
    path('services/bookings/<int:booking_id>/cancel/decline', views.decline_cancel_service_booking, name='decline_cancel_service_booking'),
    path('services/bookings/<int:booking_id>/hide', views.hide_service_booking, name='hide_service_booking'),
    # Public hospital profile (read-only)
    path('hospitals/<int:hospital_id>', views.get_hospital, name='get_hospital'),
    path('hospitals/by-user/<int:user_id>', views.get_hospital_by_user, name='get_hospital_by_user'),
    # Public doctor profile (read-only)
    path('doctors/<int:doctor_id>', views.get_doctor, name='get_doctor'),
    path('doctors/<int:doctor_id>/schedule', views.list_doctor_schedule, name='list_doctor_schedule'),
    path('appointments/book', views.book_appointment, name='book_appointment'),
    path('appointments/mine', views.list_my_appointments, name='list_my_appointments'),
    path('appointments/doctor', views.list_doctor_appointments, name='list_doctor_appointments'),
    path('appointments/<int:appointment_id>/cancel/request', views.request_cancel_appointment, name='request_cancel_appointment'),
    path('appointments/<int:appointment_id>/cancel/approve', views.approve_cancel_appointment, name='approve_cancel_appointment'),
    path('appointments/<int:appointment_id>/cancel/decline', views.decline_cancel_appointment, name='decline_cancel_appointment'),
    path('appointments/<int:appointment_id>/hide', views.hide_appointment, name='hide_appointment'),
    path('appointments/<int:appointment_id>/confirm', views.confirm_appointment, name='confirm_appointment'),
    # Phase 2 blood request & recruitment
    path('blood/requests', views.create_blood_request, name='create_blood_request'),
    path('blood/requests/list', views.list_blood_requests, name='list_blood_requests'),
    path('blood/requests/<int:request_id>', views.get_blood_request, name='get_blood_request'),
    path('blood/requests/<int:request_id>/update', views.update_blood_request, name='update_blood_request'),
    path('blood/requests/<int:request_id>/status', views.change_blood_request_status, name='change_blood_request_status'),
    path('blood/recruit', views.create_recruit_post, name='create_recruit_post'),
    path('blood/recruit/list', views.list_recruit_posts, name='list_recruit_posts'),
    path('blood/recruit/<int:post_id>', views.get_recruit_post, name='get_recruit_post'),
    path('blood/recruit/<int:post_id>/update', views.update_recruit_post, name='update_recruit_post'),
    path('blood/recruit/<int:post_id>/close', views.close_recruit_post, name='close_recruit_post'),
    path('blood/recruit/<int:post_id>/delete', views.delete_recruit_post, name='delete_recruit_post'),
    path('blood/recruit/<int:post_id>/apply', views.apply_recruit_post, name='apply_recruit_post'),
    path('blood/recruit/<int:post_id>/applications', views.list_recruit_applications, name='list_recruit_applications'),
    path('blood/applications/<int:application_id>/status', views.update_application_status, name='update_application_status'),
    path('blood/my-applications', views.my_applications, name='my_applications'),
    path('blood/overview', views.blood_overview, name='blood_overview'),
    # Blood direct requests
    path('blood/direct', views.create_blood_direct_request, name='create_blood_direct_request'),
    path('blood/direct/list', views.list_blood_direct_requests, name='list_blood_direct_requests'),
    path('blood/direct/<int:request_id>', views.get_blood_direct_request, name='get_blood_direct_request'),
    path('blood/direct/<int:request_id>/respond', views.respond_blood_direct_request, name='respond_blood_direct_request'),
    path('blood/direct/<int:request_id>/status', views.change_blood_direct_request_status, name='change_blood_direct_request_status'),
    # Blood bank org management
    path('blood-bank/donors/list', views.blood_bank_donors_list, name='blood_bank_donors_list'),
    path('blood-bank/donors/add', views.blood_bank_donors_add, name='blood_bank_donors_add'),
    path('blood-bank/donors/<int:donor_id>/update', views.blood_bank_donors_update, name='blood_bank_donors_update'),
    path('blood-bank/donors/<int:donor_id>/remove', views.blood_bank_donors_remove, name='blood_bank_donors_remove'),
    path('blood-bank/<int:bank_user_id>/donors', views.blood_bank_donors_of, name='blood_bank_donors_of'),
    path('blood-bank/staff/list', views.blood_bank_staff_list, name='blood_bank_staff_list'),
    path('blood-bank/staff/add', views.blood_bank_staff_add, name='blood_bank_staff_add'),
    path('blood-bank/staff/<int:staff_id>/update', views.blood_bank_staff_update, name='blood_bank_staff_update'),
    path('blood-bank/staff/<int:staff_id>/remove', views.blood_bank_staff_remove, name='blood_bank_staff_remove'),
    path('blood-bank/inventory/list', views.blood_inventory_list, name='blood_inventory_list'),
    path('blood-bank/inventory/set', views.blood_inventory_set, name='blood_inventory_set'),
    # Blood bank manual inventory issuances (donations from own stock)
    path('blood-bank/inventory/issue', views.blood_inventory_issue, name='blood_inventory_issue'),
    path('blood-bank/inventory/issuances', views.blood_inventory_issuances_list, name='blood_inventory_issuances_list'),
    path('blood-bank/inventory/issuances/<int:issuance_id>/update', views.blood_inventory_issuance_update, name='blood_inventory_issuance_update'),
    path('blood-bank/inventory/issuances/<int:issuance_id>/delete', views.blood_inventory_issuance_delete, name='blood_inventory_issuance_delete'),
    # Blood direct requests
    path('blood/direct', views.create_blood_direct_request, name='create_blood_direct_request'),
    path('blood/direct/list', views.list_blood_direct_requests, name='list_blood_direct_requests'),
    path('blood/direct/<int:request_id>', views.get_blood_direct_request, name='get_blood_direct_request'),
    path('blood/direct/<int:request_id>/respond', views.respond_blood_direct_request, name='respond_blood_direct_request'),
    path('blood/direct/<int:request_id>/status', views.change_blood_direct_request_status, name='change_blood_direct_request_status'),
    # Bank inventory request flow
    path('blood/inventory/request', views.create_inventory_request, name='create_inventory_request'),
    path('blood/inventory/requests', views.list_inventory_requests, name='list_inventory_requests'),
    path('blood/inventory/requests/<int:request_id>/status', views.update_inventory_request_status, name='update_inventory_request_status'),
    # Donor meeting request flow
    path('blood/donor/request', views.create_donor_meeting_request, name='create_donor_meeting_request'),
    path('blood/donor/requests', views.list_donor_meeting_requests, name='list_donor_meeting_requests'),
    path('blood/donor/requests/<int:request_id>/status', views.update_donor_meeting_request_status, name='update_donor_meeting_request_status'),
    # Donor profiles
    path('donor/profile/upsert', views.upsert_donor_profile, name='upsert_donor_profile'),
    path('donor/profile/mine', views.my_donor_profile, name='my_donor_profile'),
    path('donor/profiles/search', views.donor_profiles_search, name='donor_profiles_search'),
    path('donor/availability/set', views.set_donor_availability, name='set_donor_availability'),
    # Phase 3 campaigns
    path('campaigns', views.create_campaign, name='create_campaign'),
    path('campaigns/list', views.list_campaigns, name='list_campaigns'),
    path('campaigns/<int:campaign_id>', views.get_campaign, name='get_campaign'),
    path('campaigns/<int:campaign_id>/update', views.update_campaign, name='update_campaign'),
    path('campaigns/<int:campaign_id>/status', views.change_campaign_status, name='change_campaign_status'),
    path('campaigns/<int:campaign_id>/join', views.join_campaign, name='join_campaign'),
    path('campaigns/<int:campaign_id>/withdraw', views.withdraw_campaign, name='withdraw_campaign'),
    path('campaigns/<int:campaign_id>/participants', views.list_campaign_participants, name='list_campaign_participants'),
    path('campaigns/<int:campaign_id>/participants/<int:participant_id>/status', views.update_campaign_participant_status, name='update_campaign_participant_status'),
    path('campaigns/<int:campaign_id>/participants/<int:participant_id>', views.delete_campaign_participant, name='delete_campaign_participant'),
    path('campaigns/<int:campaign_id>/participants/add-volunteers', views.campaigns_add_volunteers, name='campaigns_add_volunteers'),
    path('campaigns/<int:campaign_id>/locations/add', views.add_campaign_location, name='add_campaign_location'),
    path('campaigns/<int:campaign_id>/locations/list', views.list_campaign_locations, name='list_campaign_locations'),
    # Campaign finance
    path('campaigns/<int:campaign_id>/donations', views.campaign_add_donation, name='campaign_add_donation'),
    path('campaigns/<int:campaign_id>/donations/list', views.campaign_list_donations, name='campaign_list_donations'),
    path('campaigns/<int:campaign_id>/expenses', views.campaign_add_expense, name='campaign_add_expense'),
    path('campaigns/<int:campaign_id>/expenses/list', views.campaign_list_expenses, name='campaign_list_expenses'),
    path('campaigns/<int:campaign_id>/finance/summary', views.campaign_finance_summary, name='campaign_finance_summary'),
    path('campaigns/mine', views.my_campaigns, name='my_campaigns'),
    path('campaigns/my-participations', views.my_campaign_participations, name='my_campaign_participations'),
    # Phase 4 fire service dispatch
    path('fire/departments', views.create_fire_department, name='create_fire_department'),
    path('fire/departments/<int:department_id>/update', views.update_fire_department, name='update_fire_department'),
    path('fire/departments/list', views.list_fire_departments, name='list_fire_departments'),
    # Public fire department profile (read-only)
    path('fire/departments/<int:department_id>', views.get_fire_department, name='get_fire_department'),
    path('fire/requests', views.fire_requests, name='fire_requests'),
    path('fire/requests/list', views.fire_requests, name='list_fire_requests'),
    # Public fire request detail (read-only)
    path('fire/requests/<int:request_id>', views.get_fire_request, name='get_fire_request'),
    path('fire/requests/<int:request_id>/assign/nearest', views.assign_fire_request_nearest, name='assign_fire_request_nearest'),
    path('fire/requests/<int:request_id>/candidate/accept', views.fire_request_candidate_accept, name='fire_request_candidate_accept'),
    path('fire/requests/<int:request_id>/candidate/decline', views.fire_request_candidate_decline, name='fire_request_candidate_decline'),
    path('fire/requests/<int:request_id>/assign', views.assign_fire_request, name='assign_fire_request'),
    path('fire/requests/<int:request_id>/status', views.change_fire_request_status, name='change_fire_request_status'),
    path('fire/requests/<int:request_id>/deploy/team', views.deploy_fire_request_team, name='deploy_fire_request_team'),
    path('fire/requests/<int:request_id>/complete', views.complete_fire_request, name='complete_fire_request'),
    path('fire/requests/<int:request_id>/cancel', views.cancel_fire_request, name='cancel_fire_request'),
    path('fire/requests/<int:request_id>/hide', views.hide_fire_request, name='hide_fire_request'),
    path('fire/activities', views.fire_activities, name='fire_activities'),
    path('fire/departments/<int:department_id>/teams/add', views.fire_department_add_team, name='fire_department_add_team'),
    path('fire/departments/<int:department_id>/teams/list', views.fire_department_list_teams, name='fire_department_list_teams'),
    path('fire/departments/<int:department_id>/teams/<int:team_id>', views.fire_department_team_item, name='fire_department_team_item'),
    path('fire/departments/<int:department_id>/teams/<int:team_id>/members/list', views.fire_department_team_members, name='fire_department_team_members'),
    path('fire/departments/<int:department_id>/teams/<int:team_id>/members/add', views.fire_department_team_add_member, name='fire_department_team_add_member'),
    path('fire/departments/<int:department_id>/teams/<int:team_id>/members/<int:member_id>/remove', views.fire_department_team_remove_member, name='fire_department_team_remove_member'),
    path('fire/departments/<int:department_id>/inventory/add', views.fire_department_add_inventory, name='fire_department_add_inventory'),
    path('fire/departments/<int:department_id>/inventory/list', views.fire_department_list_inventory, name='fire_department_list_inventory'),
    path('fire/departments/<int:department_id>/staff/add', views.fire_department_add_staff, name='fire_department_add_staff'),
    path('fire/departments/<int:department_id>/staff/list', views.fire_department_list_staff, name='fire_department_list_staff'),
    path('fire/departments/<int:department_id>/staff/<int:user_id>/remove', views.fire_department_remove_staff, name='fire_department_remove_staff'),
    path('fire/departments/<int:department_id>/staff/<int:user_id>/update', views.fire_department_update_staff, name='fire_department_update_staff'),
    path('users/search', views.search_users, name='search_users'),
    # Notifications
    path('notifications', views.list_notifications, name='list_notifications'),
    path('notifications/<int:notif_id>/read', views.mark_notification_read, name='mark_notification_read'),
    path('notifications/read-all', views.mark_all_notifications_read, name='mark_all_notifications_read'),
    path('doctor/prefs', views.doctor_prefs_get, name='doctor_prefs_get'),
    path('doctor/prefs/set', views.doctor_prefs_set, name='doctor_prefs_set'),
    path('food/donations', views.create_food_donation, name='create_food_donation'),
    path('food/donations/list', views.list_food_donations, name='list_food_donations'),
    # Social organizations
    path('social/organizations', views.add_social_organization, name='add_social_organization'),
    path('social/organizations/list', views.list_social_organizations, name='list_social_organizations'),
    path('social/organizations/mine', views.social_org_mine, name='social_org_mine'),
    # Social org volunteers
    path('social/organizations/<int:org_id>/volunteers/list', views.social_org_list_volunteers, name='social_org_list_volunteers'),
    path('social/organizations/<int:org_id>/volunteers/add', views.social_org_add_volunteer, name='social_org_add_volunteer'),
    path('social/organizations/<int:org_id>/volunteers/<int:volunteer_id>', views.social_org_volunteer_item, name='social_org_volunteer_item'),
    path('social/organizations/<int:org_id>/apply', views.social_org_apply_to_volunteer, name='social_org_apply_to_volunteer'),
    # Incidents
    path('incidents', views.create_incident, name='create_incident'),
    path('incidents/list', views.list_incidents, name='list_incidents'),
    path('incidents/<int:incident_id>', views.get_incident, name='get_incident'),
    path('incidents/<int:incident_id>/status', views.change_incident_status, name='change_incident_status'),
    path('incidents/<int:incident_id>/note', views.incident_add_note, name='incident_add_note'),
    path('incidents/<int:incident_id>/join', views.join_incident, name='join_incident'),
    path('incidents/<int:incident_id>/withdraw', views.withdraw_incident, name='withdraw_incident'),
    path('incidents/<int:incident_id>/events', views.list_incident_events, name='list_incident_events'),
    path('incidents/<int:incident_id>/participants', views.list_incident_participants, name='list_incident_participants'),
    path('incidents/<int:incident_id>/participants/<int:participant_id>', views.delete_incident_participant, name='delete_incident_participant'),
    # Incident fire team deployments
    path('incidents/<int:incident_id>/fire/deploy', views.incident_fire_deploy, name='incident_fire_deploy'),
    path('incidents/<int:incident_id>/fire/deployments', views.list_incident_fire_deployments, name='list_incident_fire_deployments'),
    path('incidents/<int:incident_id>/fire/deployments/<int:deployment_id>/status', views.incident_fire_deployment_status, name='incident_fire_deployment_status'),
    # Incident social organization volunteer deployments
    path('incidents/<int:incident_id>/social/deploy', views.incident_social_deploy, name='incident_social_deploy'),
    path('incidents/<int:incident_id>/social/deployments', views.list_incident_social_deployments, name='list_incident_social_deployments'),
    path('incidents/<int:incident_id>/social/deployments/<int:deployment_id>/status', views.incident_social_deployment_status, name='incident_social_deployment_status'),
    # Fire teams under me
    path('fire/teams/mine', views.fire_teams_mine, name='fire_teams_mine'),
    # Incident hospital resources
    path('incidents/<int:incident_id>/hospital/resources/mine', views.hospital_incident_resources_mine, name='hospital_incident_resources_mine'),
    path('incidents/<int:incident_id>/hospital/resources/set', views.hospital_incident_resources_set, name='hospital_incident_resources_set'),
    path('incidents/<int:incident_id>/hospital/resources/mine/delete', views.hospital_incident_resources_delete, name='hospital_incident_resources_delete'),
    path('incidents/<int:incident_id>/hospital/resources/list', views.list_incident_hospital_resources, name='list_incident_hospital_resources'),
    # Geo
    path('location/update', views.update_location, name='update_location'),
    path('location/nearby', views.nearby_users, name='nearby_users'),
    path('crises/nearby', views.crises_nearby, name='crises_nearby'),
    # Messaging breadth stubs
    path('conversations', views.create_conversation, name='create_conversation'),
    path('conversations/list', views.list_conversations, name='list_conversations'),
    path('conversations/<int:conversation_id>/messages', views.send_message, name='send_message'),
    path('conversations/<int:conversation_id>/messages/list', views.list_messages, name='list_messages'),
    path('conversations/<int:conversation_id>/messages/all', views.conversation_history, name='conversation_history'),
    path('inbox', views.inbox, name='inbox'),
    path('messages/direct', views.send_direct_message, name='send_direct_message'),
    path('conversations/<int:conversation_id>/messages/since', views.messages_since, name='messages_since'),
    path('inbox/updates', views.inbox_updates, name='inbox_updates'),
    path('conversations/<int:conversation_id>/read', views.conversation_mark_read, name='conversation_mark_read'),
    path('dashboard', views.dashboard, name='dashboard'),
    # Events breadth stubs
    path('events', views.create_event, name='create_event'),
    path('events/list', views.list_events, name='list_events'),
    # Diagnostics (temporary): geo population stats
    path('diag/geo-stats', views.geo_stats, name='geo_stats'),
    # Crisis management
    path('crises', views.create_crisis, name='create_crisis'),
    path('crises/list', views.list_crises, name='list_crises'),
    path('crises/<int:crisis_id>', views.get_crisis, name='get_crisis'),
    path('crises/<int:crisis_id>/completed/summary', views.crisis_completed_summary, name='crisis_completed_summary'),
    path('crises/<int:crisis_id>/invite', views.crisis_invite, name='crisis_invite'),
    path('crises/<int:crisis_id>/invitations/list', views.crisis_list_invitations, name='crisis_list_invitations'),
    path('crises/<int:crisis_id>/invitations/<int:invitation_id>/respond', views.crisis_invitation_respond, name='crisis_invitation_respond'),
    path('crises/<int:crisis_id>/invitations/<int:invitation_id>', views.crisis_delete_invitation, name='crisis_delete_invitation'),
    path('crises/invitations/mine', views.crisis_my_invitations, name='crisis_my_invitations'),
    path('crises/<int:crisis_id>/join', views.crisis_join_self, name='crisis_join_self'),
    path('crises/<int:crisis_id>/leave', views.crisis_leave_self, name='crisis_leave_self'),
    # Crisis participation request flow
    path('crises/<int:crisis_id>/participation/request', views.crisis_participation_request, name='crisis_participation_request'),
    path('crises/<int:crisis_id>/participation/requests', views.crisis_participation_requests_list, name='crisis_participation_requests_list'),
    path('crises/<int:crisis_id>/participation/requests/<int:request_id>/decide', views.crisis_participation_request_decide, name='crisis_participation_request_decide'),
    path('crises/<int:crisis_id>/participation/mine', views.crisis_participation_mine, name='crisis_participation_mine'),
    path('crises/<int:crisis_id>/donations', views.crisis_add_donation, name='crisis_add_donation'),
    path('crises/<int:crisis_id>/donations/list', views.crisis_list_donations, name='crisis_list_donations'),
    path('crises/<int:crisis_id>/expenses', views.crisis_add_expense, name='crisis_add_expense'),
    path('crises/<int:crisis_id>/expenses/list', views.crisis_list_expenses, name='crisis_list_expenses'),
    path('crises/<int:crisis_id>/finance/summary', views.crisis_finance_summary, name='crisis_finance_summary'),
    path('crises/<int:crisis_id>/victims/enroll', views.crisis_victims_enroll, name='crisis_victims_enroll'),
    path('crises/<int:crisis_id>/victims/unenroll', views.crisis_victims_unenroll, name='crisis_victims_unenroll'),
    path('crises/<int:crisis_id>/victims/<int:victim_id>/status', views.crisis_victim_status, name='crisis_victim_status'),
    path('crises/<int:crisis_id>/victims/admin/create', views.crisis_victim_admin_create, name='crisis_victim_admin_create'),
    path('crises/<int:crisis_id>/victims/<int:victim_id>', views.crisis_victim_item, name='crisis_victim_item'),
    path('crises/<int:crisis_id>/victims/<int:victim_id>/set-location', views.crisis_victim_admin_set_location, name='crisis_victim_admin_set_location'),
    path('crises/<int:crisis_id>/victims/list', views.crisis_victims_list, name='crisis_victims_list'),
    path('crises/<int:crisis_id>/potential-victims', views.crisis_potential_victims, name='crisis_potential_victims'),
    path('crises/<int:crisis_id>/requests/all', views.crisis_requests_all, name='crisis_requests_all'),
    path('crises/<int:crisis_id>/blood/inventory/summary', views.crisis_blood_inventory_summary, name='crisis_blood_inventory_summary'),
    # Participant-visible view of hospital resources (minimal) at incident scope
    path('incidents/<int:incident_id>/hospital/resources/public', views.list_incident_hospital_resources_public, name='list_incident_hospital_resources_public'),
    # Crisis-level blood bank integrations
    path('crises/<int:crisis_id>/blood/donors/list', views.crisis_blood_donors_list, name='crisis_blood_donors_list'),
    path('crises/<int:crisis_id>/blood/donors/add', views.crisis_blood_donors_add, name='crisis_blood_donors_add'),
    path('crises/<int:crisis_id>/blood/donors/<int:crisis_donor_id>/remove', views.crisis_blood_donors_remove, name='crisis_blood_donors_remove'),
    path('crises/<int:crisis_id>/blood/allocations', views.crisis_blood_allocations, name='crisis_blood_allocations'),
    path('crises/<int:crisis_id>/blood/allocations/<int:allocation_id>/update', views.crisis_blood_allocation_update, name='crisis_blood_allocation_update'),
    path('crises/<int:crisis_id>/blood/allocations/<int:allocation_id>/delete', views.crisis_blood_allocation_delete, name='crisis_blood_allocation_delete'),
]
